[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9.8.1"
  PUBLIC_API_URL = "https://taita-api.onrender.com/api"
  SITE_NAME = "Taita Blog"
  TENANT_DOMAIN = "taita.blog"

# Manejo de rutas para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Manejo de rutas de API
[[redirects]]
  from = "/api/*"
  to = "https://taita-api.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
