# Configuración para el frontend estático en Render.com
services:
  - type: web
    name: taita-frontend
    runtime: node
    region: oregon
    buildCommand: |
      npm install
      npm run build
    envVars:
      - key: PUBLIC_API_URL
        value: https://taita-api.onrender.com/api
      - key: PUBLIC_IMAGE_BASE_URL
        value: https://taita-api.onrender.com
      - key: NODE_ENV
        value: production
      - key: SITE_NAME
        value: Taita Blog
      - key: TENANT_DOMAIN
        value: taita.blog
    plan: free
