services:
  - type: web
    name: taita-frontend
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: API_URL
        value: https://taita-api.onrender.com/api
      - key: IMAGE_BASE_URL
        value: https://taita-api.onrender.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
